Counter=4

[Command_0]
Command=script-binding stats/display-stats-toggle
Order=0
OsdMessage=
Type=shortcut

[Command_1]
Command=screenshot video
Order=1
OsdMessage=${Screenshot}
Type=shortcut

[Command_2]
Command=show-text "Codec: ${video-codec} | ${width}×${height} | ${estimated-fps?.2} fps"
Order=2
OsdMessage=Codec: ${video-codec} | ${width}×${height} | ${fps} fps
Type=shortcut
