[Audio]
PreferredLanguage=jpn,jp,eng,en
Volume=100

[General]
FileDialogLastLocation=file:///home/itachi/Videos/Anime/%5BAnime Time%5D Kara No Kyoukai - Full Series %5BAll Movie%5D%5B1080p%5D%5BHEVC 10bit x265%5D%5BAAC%5D
FooterStyle=floating
LastPlayedFile=file:///home/itachi/Videos/Movies/The.Summit.Of.The.Gods.2021.1080p.BluRay.x264.AAC5.1-%5BYTS.MX%5D.mp4
LastUrl=http://ftp5.circleftp.net/FILE/Animation%20Movies/2006/Everyone%27s%20Hero%20%282006%29%20BluRay%201080p/Everyone%27s.Hero.2006.1080p.BluRay.x264-%5BYTS.AM%5D.mp4
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Playback]
OpenLastPlayedFile=true
RestoreFilePosition=true
SavePositionInterval=60

[Playlist]
PlaybackBehavior=StopAfterLast
RememberState=true

[Subtitles]
PreferredLanguage=eng,en

[Video]
ScreenshotFormat=png
ScreenshotTemplate=/home/itachi/Pictures/Haruna screenshots/%F-%n
