[Audio]
PreferredLanguage=jpn,jp,eng,en
Volume=90

[General]
FileDialogLastLocation=file:///home/itachi/Videos/Anime/Tower of God (S1+S2) %5BBD+WEB%5D %5BAV1%5D %5BItachiUchiha%5D/Tower of God (S1) %5BBD%5D %5BAV1%5D
FooterStyle=floating
LastPlayedFile=file:///home/itachi/Videos/Anime/OnePiece/%5BOne Pace%5D%5B911-912%5D Wano 03 %5B1080p%5D%5BEn Sub%5D%5B8576176D%5D.mp4
LastUrl=http://ftp5.circleftp.net/FILE/Animation%20Movies/2006/Everyone%27s%20Hero%20%282006%29%20BluRay%201080p/Everyone%27s.Hero.2006.1080p.BluRay.x264-%5BYTS.AM%5D.mp4
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true

[Playback]
OpenLastPlayedFile=true
RestoreFilePosition=true
SavePositionInterval=60

[Playlist]
PlaybackBehavior=StopAfterLast
RememberState=true
Visible=true

[Subtitles]
PreferredLanguage=eng,en

[Video]
ScreenshotFormat=png
ScreenshotTemplate=/home/itachi/Pictures/Haruna screenshots/%F-%n
